#ifndef __LMMonitor__
#define __LMMonitor__

/**
@file
Subclass of Monitor, which is generated by wxFormBuilder.
*/

#include "LM.h"

//// end generated include
#include "LandMonitorApp.h"

/** Implementing Monitor */
class LMMonitor : public Monitor
{
	protected:
		// Handlers for Monitor events.
		void m_button_psiOnButtonClick( wxCommandEvent& event );
		void m_quickBookStatusOnLeftDown( wxMouseEvent& event );
	public:
		/** Constructor */
		LMMonitor( wxWindow* parent );
	//// end generated class members
		void setSoftwareVer( const wxString &ver);
};

#endif // __LMMonitor__
